name: common_authentication
description: A new Flutter package project.
version: 0.0.1
homepage: 'https://github.com/amorenew/common_authentication'
environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  desktop_webview_auth: ^0.0.11
  equatable: ^2.0.3
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_sign_in: ^5.1.0
  cloud_firestore: ^4.2.0
  json_annotation: ^4.7.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: false
